### PR TITLE
Exercise 1,2,3,4,5 Completed (PreCourse 2).

### PR DESCRIPTION
**Pull request by priyansh22**

### CODE REVIEW

**Comment by priyansh22** [comment]
Thank you... I am not able to understand merge sort and took a little help for the Stack QuickSort question.  
Yes Will add more comments to explain the code.

**Comment by kaurramanpreet** [comment]
ohh i missed that you havent attempted the merge sort question....where are you struck in merge sort?
its okay to take help in the beginning gradually you will learn

**Comment by priyansh22** [comment]
In merge sort, I got until the recursive mergesort function, but then I am not able to understand how the elements are merged back together in a sorted order.

Yes I had taken help from geeksforgeeks for the stack portion because it I was stuck in my approach, but later I understood that part.

**Comment by kaurramanpreet** [comment]
okay so if you are clear with that quicksort ques
let me clear your doubt for merge sort

**Comment by kaurramanpreet** [comment]
see in merge sort for understanding the concept of merging 
you can think of it as like lets just take an example that we have 2 sorted arrays let them be 
2 4 6 and 3 5 9
so now how i will be doing is
i will be creating a new sorted array using 2 pointers(markers)
first marker would be pointing to head of array 1 and 2nd to the head of array 2
i will compare the first values of both the arrays like in this case 2<3 so i will insert 2 as the first element in our new array and make our 1st marker point to next value and our 2nd marker remains there only
now again i will compare the values pointed by respective markers i.e now i will be comparing 4 and 3 now as 3<4 so i will be inserting 3 in our new array and updating my 2nd marker 
then 1st marker would be at 2nd value in 1st array and 2nd marker would also be at 2nd value
now i will again compare i will find 4<5 so i will insert 4 and update my first marker
then i will be comparing 3 value of array1 and 2 valur of array 2 i.e 6 and 5 so now 5<6 so i will inseert 5 in new array and update 2nd marker and we will keep on moving till we get to the end of one of the arrays
and then append the new array with the remaining elements of the array where marker is not at the position next to the last node

**Comment by priyansh22** [comment]
Thank you so much Ramanpreet, I have clearly understood merge sort now and also completed the question. Your way of explaining was great because I was initially confused on how to merge the individual elements but using the 2 pointer trick and a new temporary array worked. 
Thank you so much.

**Pull request closed without merging**
